use_frameworks!

target 'KZFileWatchers_Example' do
  pod 'KZFileWatchers', :path => '../'

  target 'KZFileWatchers_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.10'
    pod 'Nimble', '~> 5.0'
    pod 'OHHTTPStubs/Swift', '~> 5.2'

  end
end
