use_frameworks!
platform: ios
inhibit_all_warnings

target 'KZFileWatchers_Example' do
  pod 'KZFileWatchers', :path => '../'

  target 'KZFileWatchers_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'OHHTTPStubs/Swift'

  end
end
